languageCode = 'en'
title = 'José Caique'
PygmentsCodeFences = true
PygmentsStyle = "solarized-dark256"
pluralizelisttitles = "false"
[pagination]
pagerSize = 15
disableHugoGeneratorInject = false
enableEmoji = true

[params]
description = "Senior Mobile Engineer with 9+ years experience in Android development, Kotlin Multiplatform, cross-platform solutions, and technical leadership. Remote work specialist."
favicon = "/img/favicon.ico"
customCSS = ["/css/custom.css"]

[[params.navlinks]]
name = "Posts"
url = "/posts/"

[[params.navlinks]]
name = "Talks"
url = "/talks/"

[[params.navlinks]]
name = "About"
url = "/about/"

[module]
  [[module.imports]]
    path = "github.com/mrmierzejewski/hugo-theme-console"
  [module.hugoVersion]
    extended = true
    min = "0.111.3"