baseURL = '/'
languageCode = 'en'
title = 'José Caique'
theme = 'hugo-cat'
PygmentsCodeFences = true
PygmentsStyle = "solarized-dark256"
pluralizelisttitles = "false"
paginate  = 15
disableHugoGeneratorInject = false
enableEmoji = true

[params]
ava = "/img/cat.png"
owner ="Product mobile engineer"
talk = ""
blogSection = ["blog"]
description = "José caique"
favicon = "/img/favicon.ico"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 2

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 3

[[menu.main]]
name = "About"
url = "/about/"
weight = 4

[module]
  [module.hugoVersion]
    extended = true
    min = "0.111.3"

description = "Hugo Blog Portofolio Dark theme CSS only"