languageCode = 'en'
title = 'José Caique'
theme = 'hugo-cat'
PygmentsCodeFences = true
PygmentsStyle = "solarized-dark256"
pluralizelisttitles = "false"
paginate  = 15
disableHugoGeneratorInject = false
enableEmoji = true

[params]
ava = "/img/cat.png"
owner ="Product mobile engineer"
talk = ""
blogSection = ["blog"]
description = "José caique"
favicon = "/img/favicon.ico"

[[menu.main]]
name = "Github"
url = "https://www.github.com/jcaiqueoliveira"
identifier = "/img/github.svg"
weight = 2

[[menu.main]]
name = "Linkedin"
url = "https://www.linkedin.com/in/kandadev/"
identifier = "/img/linkedin.svg"
weight = 1

[module]
  [module.hugoVersion]
    extended = true
    min = "0.111.3"